# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.IntegerField(max_length=255),
        ),
    ]
