# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-09 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20200108_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
    ]
