# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-01-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20200115_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
